/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Stan.gltf -o src/components/models/Stan.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Stan(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Stan.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RobotArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.FootL} />
          <primitive object={nodes.FootR} />
          <skinnedMesh name="Stan" geometry={nodes.Stan.geometry} material={materials.Stan_Texture} skeleton={nodes.Stan.skeleton} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Stan.gltf");
